name: 'jQuery Security Tests'

on: [pull_request, push, workflow_dispatch]

permissions:
  contents: read

jobs:
  test-security:
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@v1
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - run: npm ci
        working-directory: server
      - run: npm ci
        working-directory: test
      - run: npm test
        working-directory: test
